name: Set up project

defaults:
  run:
    shell: bash

runs:
  using: composite

  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install the project
      run: uv sync --locked --all-extras --dev
