name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  code-analysis:
    name: Code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint python files with black
        run: uv run black --diff --check $(git ls-files '*.py')

      - name: Lint python files with mypy
        run: uv run mypy $(git ls-files '*.py')

      - name: Lint python files with ruff
        run: uv run ruff check $(git ls-files '*.py')

      - name: Lint YAML files with yamllint
        run: uv run yamllint $(git ls-files '*.yml' '*.yaml')

  security:
    name: Security
    uses: ./.github/workflows/security.yml
